kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# desta forma vai ser criado um cluster k8s com mais de um nรณ
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings:
    - containerPort: 30000
      hostPort: 8080